name: 'Setup Magento'
description: 'Setup Magento'
inputs:
  php-version:
    description: 'PHP version'
    required: true
  magento-version:
    description: 'Magento version'
    required: true
outputs:
  docker-container-name:
    description: 'Docker container name'
    value: ${{ steps.variables.outputs.docker_container_name }}


runs:
  using: "composite"
  steps:
    - name: Install xmllint
      shell: bash
      run: sudo apt install -y libxml2-utils

    - name: Set variables
      shell: bash
      id: variables
      run: |
        echo "composer_name=$(cat composer.json | jq .name -r)" >> $GITHUB_OUTPUT
        echo "extension_name=$(xmllint --xpath 'string(/config/module/@name)' etc/module.xml)" >> $GITHUB_OUTPUT
        echo "directory=$(cat composer.json | jq .name -r | cut -d '/' -f2)" >> $GITHUB_OUTPUT
        echo "branch_name=continuous-integration-test-branch-v2" >> $GITHUB_OUTPUT
        echo "docker_container_name=magento-project-community-edition" >> $GITHUB_OUTPUT

    - name: Start Docker
      shell: bash
      run: PHP_VERSION=${{ inputs.php-version }} MAGENTO_VERSION=magento${{ inputs.magento-version }} docker compose -f .github/actions/setup/templates/docker-compose.yml up -d

    - name: Create branch for Composer
      shell: bash
      run: git checkout -b ${{ steps.variables.outputs.branch_name }}

    - name: Upload the code into the docker container
      shell: bash
      run: |
        docker cp $(pwd) ${{ steps.variables.outputs.docker_container_name }}:/data/extensions/ \
        && docker exec ${{ steps.variables.outputs.docker_container_name }} git config --global --add safe.directory /data/extensions/${{ steps.variables.outputs.directory }}

    - name: Install dev dependencies
      shell: bash
      run: |
        docker exec ${{ steps.variables.outputs.docker_container_name }} bash -c "composer require --dev vendic/magento-coding-standard tddwizard/magento2-fixtures"

    # We need to disable packagist.org since our extension is published there and conflicts with the local version
    # Avoids error: Higher matching version dev-main 3521d85 of vendic/magento2-admin-product-grid-category-filter was found in public repository packagist.org
    # than dev-continuous-integration-test-branch-v2 in private. Public package might've been taken over by a malicious entity, please investigate and update package
    # requirement to match the version from the private repository
    - name: Set packagist.org to false
      shell: bash
      run: |
        docker exec ${{ steps.variables.outputs.docker_container_name }}  bash -c "composer config repositories.packagist.org false"

    - name: Install the extension
      shell: bash
      run: |
        docker exec ${{ steps.variables.outputs.docker_container_name }} composer require ${{ steps.variables.outputs.composer_name }}:dev-${{ steps.variables.outputs.branch_name }}

    # Workaround for "rm: cannot remove 'generated/code/Magento': Directory not empty"
    - name: Clear generated folder
      shell: bash
      run: docker exec ${{ steps.variables.outputs.docker_container_name }} bash -c "rm -rf generated/* || (sleep 5 && rm -rf generated/*) || true"

    - name: Activate the extension
      shell: bash
      run: docker exec ${{ steps.variables.outputs.docker_container_name }} bash -c "php bin/magento module:enable ${{ steps.variables.outputs.extension_name }}"
