name: Integration
on: [push]

jobs:
  integration:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup Magento community edition
        id: setup
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          magento-version: ${{ matrix.MAGENTO_VERSION }}

      - name: Install TddWizard fixtures
        run: |
          docker exec ${{ steps.setup.outputs.docker-container-name }} bash -c "composer require --dev tddwizard/magento2-fixtures"

      - name: Run tests
        run: docker exec ${{ steps.setup.outputs.docker-container-name }} bash -c "cd /data/dev/tests/integration/ && ../../../vendor/bin/phpunit"

