name: phpstan
on: [push]

env:
  temp-branch: continuous-integration-test-branch-v2

jobs:
  phpstan:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt install -y libxml2-utils

      - name: Get extension name
        id: extension_name
        run: |
          echo "composer_name=$(cat composer.json | jq .name -r)" >> $GITHUB_OUTPUT
          echo "extension_name=$(xmllint --xpath 'string(/config/module/@name)' etc/module.xml)" >> $GITHUB_OUTPUT
          echo "directory=$(cat composer.json | jq .name -r | cut -d '/' -f2)" >> $GITHUB_OUTPUT

      - name: Start Docker
        run: PHP_VERSION=${{ matrix.PHP_VERSION }} MAGENTO_VERSION=magento${{ matrix.MAGENTO_VERSION }} docker compose -f .github/workflows/templates/docker-compose.yml up -d

      - name: Create branch for Composer and remove version from composer.json
        run: git checkout -b ${{ env.temp-branch }} && sed -i '/version/d' ./composer.json

      - name: Upload the code into the docker container
        run: |
          docker exec magento-project-community-edition composer require ${{ steps.extension_name.outputs.composer_name }}:"@dev"

      - name: Activate the extension
        run: docker exec magento-project-community-edition bash -c "php bin/magento module:enable ${{ steps.extension_name.outputs.extension_name }}"

      - name: Run PHPStan
        run: docker exec magento-project-community-edition /bin/bash -c "./vendor/bin/phpstan analyse --no-progress -c /data/extensions/*/phpstan.neon /data/extensions"
